---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
library(marmap)
library(ggplot2)
library(reticulate)
library(tidyverse)
```
```{python import}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy.polynomial.polynomial import polyfit
```


## The information about columns
```{python}
df = pd.read_csv("../data/historic_nfl_elo.csv").set_index("Unnamed: 0")
df.info()
```

## Correlation between columns
```{python}
corr = df.corr()
# The line below couldn't render correctly in Rmarkdown
# corr.style.background_gradient(cmap='coolwarm', axis=None).set_precision(2)
corr#.style.background_gradient(cmap='coolwarm', axis=None).set_precision(2)
```

## Because of the major rule change effective in 1970, remove data points before 1970
```{python}
df_table = df[['season', 'playoff', 'elo1_pre', 'elo2_pre', 'elo_prob1', 'elo_prob2',
       'elo1_post', 'elo2_post', 'qbelo1_pre', 'qbelo2_pre', 'qbelo_prob1', 'qbelo_prob2', 'score1', 'score2']]
df_table = df_table[df_table['season']>1969]
df_table = df_table[df_table['season']<2019]
df_table['decade'] = (df_table["season"]//10)*10
df_table
```

## Plot for season games
```{python}
df_xs_reg = df_table[df_table['playoff'].isna()]
df_xs_reg['elo_diff'] = df_xs_reg['elo1_pre'] - df_xs_reg['elo2_pre']
df_xs_reg['score_diff'] = df_xs_reg['score1'] - df_xs_reg['score2']
df_xs_reg['is_winner'] = np.where(df_xs_reg['score_diff'] > 0, 1, 0)
df_xs_reg['elo_change_aftergame']= df_xs_reg['elo1_post'] - df_xs_reg['elo1_pre']
df_xs_reg

x = np.array(df_xs_reg['elo_diff'])
y = np.array(df_xs_reg['score_diff'])
y0, m = polyfit(x, y, 1)

x2 = np.array(df_xs_reg['elo_change_aftergame'])
y2 = np.array(df_xs_reg['score_diff'])
c2 = np.array(df_xs_reg['is_winner'])

fig, ax = plt.subplots()
ax.scatter(x, y, alpha = 0.2)
ax.plot(x, y0 + m * x, color='red')
ax.set(xlabel='difference in ELO', 
        ylabel='difference in score', title = 'Score vs pre-game ELO')
ax.legend()
ax.grid()
fig.savefig("score_vs_pregame_elo.png")
plt.show()

fig2, ax2 = plt.subplots()
ax2.scatter(x2, y2, c=c2, alpha = 0.2)
ax2.set(xlabel='change in elo after game',
        ylabel = 'difference in score', title = 'Post-game ELO vs result')
ax2.legend(loc = 'lower right')
ax2.grid()
plt.show()
```

```{r plot}
py$df_xs_reg %>%
  mutate(is_winner = if_else(is_winner == 1, 'win', 'lose')) %>% ggplot() +
  geom_point(aes(x = elo_change_aftergame, y = score_diff, color = is_winner))
```